flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:Skyfold/text-show.git
    commit: e5b365c4176ef72b624f1e5509aac960e4cd7b6e
  extra-dep: true 
extra-deps:
- base-compat-0.9.1
- base-orphans-0.5.4
- generic-deriving-1.10.4.1
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- transformers-compat-0.5.1.4
resolver: nightly-2016-03-21
